import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillYoutube,
  AiFillHome,
  AiFillInfoCircle,
  AiFillCode,
  AiFillAppstore
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import { useState } from "react";
import { Cursor, useTypewriter } from "react-simple-typewriter";
import { motion } from "framer-motion";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [text, count] = useTypewriter({
    words: ["I'm a Fullstack Developer.", "I love games.", "I love music."],
    loop: true,
    delaySpeed: 2000,
  });
  return (
    <div className={darkMode ? "dark font-InterTight" : "font-InterTight"}>
      <Head>
        <title>Kraytage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 scroll-smooth scrollbar h-screen scrollbar-track-teal-700 scrollbar-thumb-teal-200 dark:bg-gray-900 md:overflow-y-hidden md:overflow-x-hidden">
        <section id="welcome">
          {/*Navigasyon*/}
          <nav className="py-10 mb-12 flex justify-between">
            <motion.h1
              initial={{
                x: -500,
                opacity: 0,
                scale: 0.5,
              }}
              animate={{
                x: 0,
                opacity: 1,
                scale: 1,
              }}
              transition={{
                duration: 1.5,
              }}
              className=" text-2xl font-burtons dark:text-teal-200"
            >
              kraytage
            </motion.h1>
            <motion.ul
              initial={{
                x: 500,
                opacity: 0,
                scale: 0.5,
              }}
              animate={{
                x: 0,
                opacity: 1,
                scale: 1,
              }}
              transition={{
                duration: 1.5,
              }}
              className=" flex items-center"
            >
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                  className=" cursor-pointer text-2xl  text-teal-600"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#services"
                >
                  Resume
                </a>
              </li>
            </motion.ul>
          </nav>
          {/* Ana giriş*/}
          <div className=" min-h-screen relative">
            <div className=" invisible fixed pb-96 min-h-screen text-teal-600 flex items-center lg:visible">
              <ul className="text-2xl">
                <li className="py-6"><a href="#welcome"><AiFillHome /></a></li>
                <li className="py-6"><a href="#about_me"><AiFillInfoCircle /></a></li>
                <li className="py-6"><a href="#services"><AiFillCode /></a></li>
                <li className="py-6"><a href="#portfolio"><AiFillAppstore /></a></li>
              </ul>
            </div>
            <div className=" text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl md:mt-28">
                Eray Kırkpınar
              </h2>
              <h3 className="text-2xl py-2 md:text-3xl dark: text-teal-400">
                {text}
                <Cursor cursorColor="rgb(153 246 228)" />
              </h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-teal-200">
                I am Eray Kırkpınar and I use{" "}
                <span className="text-teal-500">Kraytage</span> as a nickname on
                <br />
                social media. I love games and music.
              </p>
            </div>

            {/* Sosyal Medya */}
            <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
          </div>
        </section>
        <section id="about_me">
          {/*Hoşgeldin fotoğrafı */}
          <div className=" min-h-screen  text-center pt-16">
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mb-16 overflow-hidden">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
            <h3 className="text-4xl text-teal-400">About Me</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-teal-200">
              Hello there! My name is Eray and I enjoy creating living things on
              the internet. My interest in programming started in 2007 when I
              bought my first computer. After dealing with{" "}
              <span className="text-teal-500">HTML</span> and{" "}
              <span className="text-teal-500">CSS</span> for a while, I learned{" "}
              <span className="text-teal-500">Python</span> and{" "}
              <span className="text-teal-500">C#</span>. All this made me a{" "}
              <span className="text-teal-500">Fullstack Developer.</span>
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-teal-200">
              Here are a few technologies I’ve been working with recently:
            </p>
            <div className="flex justify-center gap-20">
              <ul className="list-disc">
                <li className="text-xl text-teal-400 text-left">Python</li>
                <li className="text-xl text-teal-400 text-left">C# / .Net</li>
                <li className="text-xl text-teal-400 text-left">React.js</li>
                <li className="text-xl text-teal-400 text-left">Next.js</li>
              </ul>
              <ul className="list-disc">
                <li className="text-xl text-teal-400 text-left">
                  Premiere Pro
                </li>
                <li className="text-xl text-teal-400 text-left">
                  Davinci Resolve
                </li>
                <li className="text-xl text-teal-400 text-left">
                  After Effects
                </li>
                <li className="text-xl text-teal-400 text-left">Photoshop</li>
              </ul>
            </div>
          </div>
        </section>
        {/*Kartlar*/}
        <section id="services" className="min-h-screen py-24 md:px-32">
          <div className="text-center">
            <h3 className=" text-4xl py-1 mb-5 dark:text-teal-400">
              Services I Offer
            </h3>
            <p className="text-xl leading-8 text-gray-800 dark:text-teal-200">
              Lorem <span className="text-teal-500">ipsum</span> dolor sit amet,
              consectetur adipiscing elit. Praesent ligula nisi, lobortis et
              porttitor id.
            </p>
            <p className="text-xl leading-8 text-gray-800 dark:text-teal-200">
              Sodales a arcu. Nunc feugiat blandit sem, sit amet ullamcorper
              lorem accumsan a. In eros.
            </p>
          </div>
          {/*Kart1*/}
          <div className=" lg:flex gap-10 mt-12">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image src={design} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-teal-400">
                Beautiful Designs
              </h3>
              <p className=" py-2 dark:text-teal-200">
                Lorem <span className="text-teal-500">ipsum</span> dolor sit
                amet, consectetur adipiscing elit. Praesent ligula nisi,
                lobortis et porttitor id.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-teal-200">
                Photoshop
              </p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Blender</p>
            </div>
            {/*Kart2*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image src={code} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-teal-400">
                Beautiful Designs
              </h3>
              <p className=" py-2 dark:text-teal-200">
                Lorem <span className="text-teal-500">ipsum</span> dolor sit
                amet, consectetur adipiscing elit. Praesent ligula nisi,
                lobortis et porttitor id.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-teal-200">
                Photoshop
              </p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Blender</p>
            </div>
            {/*Kart3*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image src={consulting} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-teal-400">
                Beautiful Designs
              </h3>
              <p className=" py-2 dark:text-teal-200">
                Lorem <span className="text-teal-500">ipsum</span> dolor sit
                amet, consectetur adipiscing elit. Praesent ligula nisi,
                lobortis et porttitor id.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-teal-200">
                Photoshop
              </p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Blender</p>
            </div>
          </div>
        </section>
        {/*Portfolio*/}
        <section id="portfolio" className="min-h-screen pt-16 md:px-32">
          <div className="text-center">
            <h3 className=" text-4xl py-1 mb-5 dark:text-teal-400">
              Portfolio
            </h3>
            <p className=" py-2  text-xl dark:text-teal-200">
              Lorem <span className="text-teal-500">ipsum</span> dolor sit amet,
              consectetur adipiscing elit. Pellentesque egestas rutrum dolor,
              consectetur consequat nibh malesuada ac. Donec tristique vel odio
              rhoncus tempus. Sed vitae velit gravida, rhoncus dui nec, mattis
              risus. Morbi placerat blandit mi. Donec congue auctor auctor.
              Vestibulum nec dolor a eros lobortis volutpat. Cras nec nibh.
            </p>
            <p className=" py-2 text-xl dark:text-teal-200">
              Morbi placerat blandit mi. Donec congue auctor auctor. Vestibulum
              nec dolor a eros lobortis volutpat. Cras nec nibh.
            </p>
          </div>
          {/*Galeri*/}
          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
