import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark font-InterTight" : "font-InterTight"}>
      <Head>
        <title>Kraytage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          {/*Navigasyon*/}
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-2xl font-burtons dark:text-teal-200">
              kraytage
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                  className=" cursor-pointer text-2xl  text-teal-600"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {/* Ana giriş*/}
          <div className=" text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl md:mt-28">
              Kraytage
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark: text-teal-400">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-teal-200">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
              ligula nisi, lobortis et porttitor id, sodales a arcu. Nunc
              feugiat blandit sem, sit amet ullamcorper lorem accumsan a. In
              eros.
            </p>
          </div>
          {/* Sosyal Medya */}
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          {/*Hoşgeldin fotoğrafı */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-32 mb-32 overflow-hidden md:h-96 md:w-96 md:mt-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        {/*Kartlar*/}
        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-teal-400">
              Services I Offer
            </h3>
            <p className="text-md -py-2 leading-8 text-gray-800 dark:text-teal-200">
              Lorem <span className="text-teal-500">ipsum</span> dolor sit amet,
              consectetur adipiscing elit. Praesent ligula nisi, lobortis et
              porttitor id.
            </p>
            <p className="text-md -py-2 leading-8 text-gray-800 dark:text-teal-200">
              Sodales a arcu. Nunc feugiat blandit sem, sit amet ullamcorper
              lorem accumsan a. In eros.
            </p>
          </div>
          {/*Kart1*/}
          <div className=" lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image src={design} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-teal-400">
                Beautiful Designs
              </h3>
              <p className=" py-2 dark:text-teal-200">
                Lorem <span className="text-teal-500">ipsum</span> dolor sit
                amet, consectetur adipiscing elit. Praesent ligula nisi,
                lobortis et porttitor id.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-teal-200">
                Photoshop
              </p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Blender</p>
            </div>
            {/*Kart2*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image src={code} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-teal-400">
                Beautiful Designs
              </h3>
              <p className=" py-2 dark:text-teal-200">
                Lorem <span className="text-teal-500">ipsum</span> dolor sit
                amet, consectetur adipiscing elit. Praesent ligula nisi,
                lobortis et porttitor id.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-teal-200">
                Photoshop
              </p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Blender</p>
            </div>
            {/*Kart3*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image src={consulting} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-teal-400">
                Beautiful Designs
              </h3>
              <p className=" py-2 dark:text-teal-200">
                Lorem <span className="text-teal-500">ipsum</span> dolor sit
                amet, consectetur adipiscing elit. Praesent ligula nisi,
                lobortis et porttitor id.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-teal-200">
                Photoshop
              </p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-teal-200">Blender</p>
            </div>
          </div>
        </section>
        {/*Portfolio*/}
        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-teal-400">Portfolio</h3>
            <p className=" py-2 dark:text-teal-200">
              Lorem <span className="text-teal-500">ipsum</span> dolor sit amet,
              consectetur adipiscing elit. Pellentesque egestas rutrum dolor,
              consectetur consequat nibh malesuada ac. Donec tristique vel odio
              rhoncus tempus. Sed vitae velit gravida, rhoncus dui nec, mattis
              risus. Morbi placerat blandit mi. Donec congue auctor auctor.
              Vestibulum nec dolor a eros lobortis volutpat. Cras nec nibh.
            </p>
            <p className=" py-2 dark:text-teal-200">
              Morbi placerat blandit mi. Donec congue auctor auctor. Vestibulum
              nec dolor a eros lobortis volutpat. Cras nec nibh.
            </p>
          </div>
          {/*Galeri*/}
          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
