// Home.js
import React from "react";
import Head from "next/head";
import Navigation from "./Navigation";
import Introduction from "./Introduction";
import FixedMenu from "./FixedMenu";
import AboutMe from "./AboutMe";
import Cards from "./Cards";
import Portfolio from "./Portfolio";

function Home() {
    return (
        <div className="dark font-Coolvetica">
            <Head>
                <title>Kray</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-eray px-10 md:px-20 lg:px-40 scroll-smooth scrollbar h-screen scrollbar-track-gray-900 scrollbar-gray-900 dark:bg-eray md:overflow-y-hidden md:overflow-x-hidden">
                <section id="welcome" className="h-screen">
                    {/* Navigation */}
                    <Navigation />

                    {/* Introduction */}
                    <Introduction />

                    {/* Fixed Menu */}
                    <FixedMenu />
                </section>
                <section id="about" className="h-screen">
                    <AboutMe />
                </section>
                <section id="services" className="h-screen">
                    <Cards/>
                </section>
                <section id="portfolio">
                    <Portfolio/>
                </section>
            </main>
        </div >
    );
}

export default Home;
